# ansible n1 -m file -a "path=/home/fedora/opt/n1_dir state=directory"
---
- name: Update n1 servers
  hosts: n1
  become: yes  # Ensures the playbook runs with sudo privileges

  tasks:
    - name: Create directory
      file:
        path: /home/fedora/opt/devops_dir
        state: directory
        owner: fedora
        group: fedora
        mode: '0755'
...
