---
- name: Update all servers
  hosts: all
  become: yes  # Ensures the playbook runs with sudo privileges

  tasks:
    - name: Create directory
      file:
        path: /home/fedora/opt/devops_dir
        state: directory
        owner: fedora
        group: fedora
        mode: '0755'
...
