# ansible n1 -m file -a "path=/home/fedora/opt/n1_dir state=directory"
---
- name: Update n1 servers
  hosts: n1
  become: yes  # Ensures the playbook runs with sudo privileges

  tasks:
    - name: Create directory
      file:
        path: /home/fedora/opt/devops_dir
        state: directory

- name: Create directory
      file:
        path: /home/fedora/opt/devops_dir_1
        state: directory

- name: Update n2 servers
  hosts: n2
  become: yes  # Ensures the playbook runs with sudo privileges

  tasks:
    - name: Create directory
      file:
        path: /home/fedora/opt/devops_dir_1
        state: directory

    - name: Create directory
      file:
        path: /home/fedora/opt/devops_dir_2
        state: directory

- name: Update group1 servers
  hosts: g1
  become: yes  # Ensures the playbook runs with sudo privileges

  tasks:
    - name: Create directory
      file:
        path: /home/fedora/opt/devops_dir_group1
        state: directory

    - name: Create directory
      file:
        path: /home/fedora/opt/devops_dir_group2
        state: directory   ...
